### ISSUE TITLE
Ability to request pwnedpasswords by prefix

### ISSUE THREAD

**Issue by binaek** [wneessen/go-hibp#14]

**Comment by wneessen** [comment]
Hi,

can you please eleborate a bit more what exactly you are looking for and what you mean by "prefix"?

**Comment by wneessen** [comment]
You can either use [CheckPassword()](https://pkg.go.dev/github.com/wneessen/go-hibp#PwnedPassApi.CheckPassword) or [CheckSHA1()](https://pkg.go.dev/github.com/wneessen/go-hibp#PwnedPassApi.CheckSHA1) to access the password API. Both with return a [Match](https://pkg.go.dev/github.com/wneessen/go-hibp#Match) type which has a `Count` property that will give you access to the amount of matches and a `Hash` property that holds the full hash. Does that give you the information you are looking for or what exactly are you looking for instead? Could you provide an example?

**Comment by binaek** [comment]
The API Endpoint may return multiple hashes for a `5 char` prefix. e.g: https://api.pwnedpasswords.com/range/21BD1

It will be great if I could access all the hashes - not just the one.

i.e: I need to search with a Prefix and not necessarily with the whole hash.

**Comment by wneessen** [comment]
Understood. Should be possible to implement. I'll check what would be the best way to implement this.

**Comment by wneessen** [comment]
Just to clarify... would you like to be able to receive the hash list from a prefix no mater if a password matches or only if a password matches?

**Comment by binaek** [comment]
I think a `CheckPrefix` should cover the need. A full hash list may potentially include the paddings as well, which is essentially junk data to put the needle in a haystack.

Something like `func (p *PwnedPassApi) CheckSHA1Prefix(prefix string) ([]*Match, *http.Response, error)`

**Comment by wneessen** [comment]
I've commited https://github.com/wneessen/go-hibp/commit/05ea767ee1057070d3834a291f6329f6b6824adb and merged it to main. It implements 3 new methods: `ListHashesPrefix()` (which is basically the previously private method `apiCall()`), `ListHashesSHA1()` and `ListHashesPassword()` which all return the match list based on the given value. I did not name it `Check*()` to keep consistency in the naming schema.

Hope this fits your needs. If not, please let me know what should be changed. I've not released it yet, since I'd like your feedback first.

**Comment by binaek** [comment]
@wneessen thank you for the quick turnaround. The API looks good! Let me get back to you as soon as I have tried it out.

**Comment by wneessen** [comment]
Thanks for verifying. Good point about the padding results.
PR https://github.com/wneessen/go-hibp/pull/16 will remove the zero-hashes from the result list which should hopefully address your issue.

**Comment by wneessen** [comment]
https://github.com/wneessen/go-hibp/releases/tag/v1.0.3 has now been released, so that you can fetch the latest version directly via Go's pkg mechanism.
