### ISSUE TITLE
Should return http.Response for paste?

### ISSUE THREAD

**Issue by chandru89new** [wneessen/go-hibp#22]
In [this code](https://github.com/wneessen/go-hibp/blob/8a77d77ee65b5b77f736328abf78d952697d1096/paste.go#L46-L48):

```go
        hb, hr, err := p.hibp.HTTPResBody(http.MethodGet, apiURL, nil)
	if err != nil {
		return nil, nil, err
	}
```

the http response is ignored and `nil` returned if there is any error. However, the error might come from the API call, in which case there could be a response and should be passed down this method as well. Is `nil` being returned intentionally?

**Comment by wneessen** [comment]
Good catch. Thanks for the report. That's definitely an oversight and not intended. I'll fix that tomorrow and create a new release.

**Comment by chandru89new** [comment]
Hi @wneessen thanks for the quick fix. The issue exists in `breach`, `password` APIs as well (sorry I just noticed it).

**Comment by wneessen** [comment]
Yeah, I am already working on the `breaches` fix as well, but wanted to keep it as a separate commit. In fact I am currently overhauling the whole error handling a bit. All coming commits will be put together in the next release.

**Comment by wneessen** [comment]
Version 1.0.5 has just been released with the corresponding fixes.
https://github.com/wneessen/go-hibp/releases/tag/v1.0.5

**Comment by wneessen** [comment]
Appreciate it!
