### ISSUE TITLE
Possible index out of range panic

### ISSUE THREAD

**Issue by KenjiTakahashi** [wneessen/go-hibp#34]
Stacktrace piece:
```
out of range [1] with length 1
goroutine 335253 [running]:
runtime/debug. Stack()
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/debug/stack.go:24 +0x64
/opt/homebrew/Cellar/go/1.22.2/libexec/src/runtime/panic.go:770 +0x124
github.com/wneessen/go-hibp.(*PwnedPassAPI).ListHashesPrefix(0x1400243cdaD, {0x14003450210,
0x5})
/Users/kenji/.go/pkg/mod/github.com/wneessen/go-hibp@v1.0.6/password.go:209 +0x664
github.com/wneessen/go-hibp.(*PwnedPassAPI).CheckSHA1(0x105586fbe?,
(0x14003450210, 0x28})
/Users/kenji/.go/pkg/mod/github.com/wneessen/go-hibp@v1.0.6/password.go:77 +0x40
github.com/wneessen/go-hibp. (*PwnedPassAPI).CheckPassword(0x1400243cdaD, {0x140022da510?, 0x14001576690?})
/Users/kenji/•go/pkg/mod/github.com/wneessen/go-hibp@v1.0.6/password.go:59 +0x1a0
```

This was caught by our E2Es with random input data, so unfortunately I can't tell if it is some specific input that triggers it or maybe it's a "glitch" in the API output. It did happen on multiple different runs over time, though.
And I'd say it should not panic either way.

**Comment by wneessen** [comment]
Appreciate the report @KenjiTakahashi. I'll look into it the next days. I guess there is a nil check missing.

**Comment by wneessen** [comment]
HI again @KenjiTakahashi,

I'm pretty sure I've seen this before and already fixed it via https://github.com/wneessen/go-hibp/commit/f387547749c72a712c99b61236735e00ee93e723 in the main branch. Would you be able to test this using the main branch?

**Comment by KenjiTakahashi** [comment]
Ah, yes, looks like this fixes it. As far as I can tell, it does not trigger reliably in the tests. But the code change makes sense, too.
Any chances of tagging a new release with the fix?

**Comment by wneessen** [comment]
Thanks for confirming. I'll tag a new release right now.

**Comment by wneessen** [comment]
v1.0.7 is now live: https://github.com/wneessen/go-hibp/releases/tag/v1.0.7

**Comment by KenjiTakahashi** [comment]
Great, thanks!
